### ISSUE TITLE
Error when executing FSharpLint.Core under unit tests

### ISSUE THREAD

**Issue by dungpa** [fsprojects/FSharpLint#118]
I write unit tests that uses FSharpLint.Core at https://github.com/dungpa/PowerTools/tree/lint-tests

I've got this exception when running with Visual Studio test runner:

```
Fail: The following exception occurs inside async blocks: System.TypeInitializationException: The type initializer for '<StartupCode$FSharpLint-Application>.$Lint' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharpLint-Framework>.$LoadVisitors' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\abc\AppData\Local\Temp\nunit20\ShadowCopyCache\8132_635746774310066866\Tests_1388807402\assembly\dl3\ebca1bf3\00ec133a_46c1d001\FSharpLint.Rules.dll' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at <StartupCode$FSharpLint-Framework>.$LoadVisitors..cctor()
   --- End of inner exception stack trace ---
   at FSharpLint.Framework.LoadVisitors.get_rulesAssembly()
   at <StartupCode$FSharpLint-Application>.$Lint..cctor()
   --- End of inner exception stack trace ---
   at FSharpLint.Application.Lint.LoadPlugins.get_plugins()
   at FSharpLint.Application.Lint.lintParsedFile(OptionalLintParameters optionalParams, ParsedFileInformation parsedFileInfo, String filepath)
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintTagger.clo@34-326.Invoke(ParsedInput _arg4) in C:\Users\abc\Documents\GitHub\PowerTools\src\FSharpVSPowerTools.Logic\LintTagger.fs:line 34
   at <StartupCode$FSharpVSPowerTools-Core>.$Utils.Bind@319-4.Invoke(Unit unitVar) in C:\Users\abc\Documents\GitHub\PowerTools\src\FSharpVSPowerTools.Core\Utils.fs:line 321
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
MockServiceProvider.GetService(SVsActivityLog)
Error//F# Power Tools//Exception Message: The type initializer for '<StartupCode$FSharpLint-Application>.$Lint' threw an exception.
Stack Trace:    at FSharpLint.Application.Lint.LoadPlugins.get_plugins()
   at FSharpLint.Application.Lint.lintParsedFile(OptionalLintParameters optionalParams, ParsedFileInformation parsedFileInfo, String filepath)
   at <StartupCode$FSharpVSPowerTools-Logic>.$LintTagger.clo@34-326.Invoke(ParsedInput _arg4) in C:\Users\abc\Documents\GitHub\PowerTools\src\FSharpVSPowerTools.Logic\LintTagger.fs:line 34
   at <StartupCode$FSharpVSPowerTools-Core>.$Utils.Bind@319-4.Invoke(Unit unitVar) in C:\Users\abc\Documents\GitHub\PowerTools\src\FSharpVSPowerTools.Core\Utils.fs:line 321
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
```

Perhaps `FSharpLint.Core` uses some reflection tricks to setup plugins. What do I have to do so that plugin discovery doesn't fail under tests?

**Comment by duckmatt** [comment]
It will need `FSharpLint.Rules.dll` in the same directory as `FSharpLint.Framework.dll`: https://github.com/fsprojects/FSharpLint/blob/master/src/FSharpLint.Framework/LoadVisitors.fs#L32 Looks like this could be causing some problems as it looks like the dlls are getting cached in different directories

If this is problematic I'll look at taking the reflection out as I don't think it's as helpful as it was originally planned to be

**Comment by dungpa** [comment]
I confirm that these two assemblies are on the same location.

The issue is due to Shadow Copy of assemblies. The test  runs fine using TestDriven.net test runner.

Here is a relevant bit from NUnit website http://www.nunit.org/index.php?p=optionsDialog&r=2.4.8 (emphasis mine):

> Shadow Copy

> NUnit normally uses .Net shadow-copying in order to allow you to edit and recompile assemblies while it is running. Uncheck this box to disable shadow-copy only if you have a particular problem that requires it.

> **Note: If you are tempted to disable shadow copy in order to access files in the same directory as your assembly, you should be aware that there are alternatives. Consider using the Assembly.Codebase property rather than Assembly.Location.**

Would you consider to make this change?

**Comment by duckmatt** [comment]
Thanks, with [`0.0.6`](https://www.nuget.org/packages/FSharpLint.Core/0.0.6) this should no longer be an issue, this version is also now using fsharp.compiler.service `1.4.0.1`

**Comment by dungpa** [comment]
Sweet. Thanks.
