### ISSUE TITLE
FAKE task failing after first run.

### ISSUE THREAD

**Issue by duckmatt** [fsprojects/FSharpLint#121]
First run successfully completes, but after that it fails with the following:

    ..\..\packages\FAKE\tools\FAKE.exe testLintViaFake.fsx Lint
    Building project with version: LocalBuild
    Shortened DependencyGraph for Target Lint:
    <== Lint

    The resulting target order is:
     - Lint
    Starting Target: Lint
    Running build failed.
    Error:
    System.InvalidCastException: Unable to cast transparent proxy to type 'FSharpLint.Worker.IFSharpLintWorker'.
       at FSharpLint.Application.AppDomainWorker.AppDomainWorker.getWorker(AppDomain appDomain)
       at FSharpLint.Application.AppDomainWorker.AppDomainWorker.RunLint(String projectFile, LintOptions options)
       at FSharpLint.FAKE.FSharpLint(FSharpFunc`2 setParams, String projectFile)
       at FSI_0001.TestLintViaFake.clo@9-2.Invoke(String projectFile)
       at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
       at FSI_0001.TestLintViaFake.clo@9.Invoke(Unit _arg1)
       at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 481

Appears to be related to some kind of caching in the `.fake` directory

**Comment by archaeron** [comment]
I have this error even when I delete every file in the `.fake`directory. It happened the first time as well.

**Comment by duckmatt** [comment]
Thanks for letting me know, I'm going to try to get it running in the same app domain as FAKE

**Comment by archaeron** [comment]
awesome, thanks :)

**Comment by duckmatt** [comment]
This has been fixed here: https://github.com/fsprojects/FSharpLint/pull/153 - will be included in next release
