### ISSUE TITLE
FSharpLint.Fake terminated in StackOverflowException

### ISSUE THREAD

**Issue by anthonyshull** [fsprojects/FSharpLint#246]
### Description

Using Fake I cannot lint a project.

### Repro steps

Create a project with Visual Studio Code. Add the following to build.fsx:

```
#I @"packages/FSharpLint.Fake/tools"
#r @"packages/FSharpLint.Fake/tools/FSharpLint.Fake.dll"

open FSharpLint.Fake

Target "Lint" (fun _ -> FSharpLint id "Project.Core/Project.Core.fsproj")
```

### Expected behavior

The Linter runs.

### Actual behavior

Receive error:
```
Process is terminated due to StackOverflowException.
Failed to lint Project.Core/Project.Core.fsproj. Failed with: Lint failed while analysing Project.Core/Project.Core.fsproj.
Failed with: Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''. 
Stack trace:    at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCracker.GetProjectOptionsFromProjectFileLogged(String projectFileName, FSharpOption`1 properties, FSharpOption`1 loadedTimeStamp, FSharpOption`1 enableLogging)
   at FSharpLint.Application.Lint.getProjectFileInfo(String projectFilePath)
   at FSharpLint.Application.Lint.lintProject(OptionalLintParameters optionalParams, String projectFilePath, FSharpOption`1 progress)
   at FSharpLint.Application.FSharpLintWorker.RunLint(String projectFile, OptionalLintParameters options, FSharpOption`1 progress)
```
### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Operating system: Windows 10 x64
* .NET 4.6.1

**Comment by duckmatt** [comment]
Hello, thank you for reporting this. Would you also be able to provide the fsproj file please?

**Comment by anthonyshull** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net461</TargetFramework>
    <DebugType>portable</DebugType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Project.Core.fs" />
    <None Include="Script.fsx" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
```

**Comment by duckmatt** [comment]
Thanks for raising this, and sorry for the very delayed response! The Fake task has been deprecated for now, the linter is now best run as [dotnet tool](https://www.nuget.org/packages/dotnet-fsharplint/) or via Ionide. Although saying this the Fake task will probably come back as a wrapper around executing the dotnet tool
