### ISSUE TITLE
Intermittent ObjectDisposedException in 0.9.1-beta MSBuild task

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/FSharpLint#262]
### Description

As per title.  Happens a few percent of the time in a case where `dotnet fake` is building an old-school .net framework solution with FSharpLint as the MSBuild task.

### Repro steps

My repro steps are -- build my [`altcover`](https://github.com/SteveGilham/altcover) repo; it fails occasionally.

### Expected behavior

No exceptions.

### Actual behavior

```
error : Exception: Lint failed while analysing C:\projects\altcover\AltCover.Recorder\AltCover.Recorder.fsproj.
error : Failed with: The CancellationTokenSource has been disposed.
error : Stack trace:    at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
error :    at <StartupCode$FSharp-Compiler-Service>.$Service.CheckFileInProject@2556-1.Invoke(Unit unitVar)
error :    at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
error : --- End of stack trace from previous location where exception was thrown ---
error :    at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
error :    at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
error :    at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
error :    at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
error :    at FSharpLint.Framework.ParseFile.typeCheckFile@45(String file, String source, FSharpProjectOptions options, FSharpChecker checker, FSharpParseFileResults parseResults, Unit unitVar0)
error :    at FSharpLint.Framework.ParseFile.parse[a](a configuration, String file, String source, FSharpChecker checker, FSharpProjectOptions options)
error :    at FSharpLint.Framework.ParseFile.parseFile[a](String file, a configuration, FSharpChecker checker, FSharpOption`1 projectOptions)
error :    at FSharpLint.Application.Lint.parsedFiles@369.Invoke(String file)
error :    at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x)
error :    at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
error :    at FSharpLint.Application.Lint.parseFilesInProject@352(OptionalLintParameters optionalParams, FSharpFunc`2 projectProgress, FSharpFunc`2 warningReceived, FSharpChecker checker, Configuration config, FSharpList`1 files, FSharpProjectOptions projectOptions)
error :    at FSharpLint.Application.Lint.loadConfigAndParseFilesInProject@382(OptionalLintParameters optionalParams, String projectFilePath, FSharpFunc`2 projectProgress, FSharpFunc`2 warningReceived, FSharpChecker checker, FSharpList`1 files, FSharpProjectOptions projectOptions)
error :    at FSharpLint.Application.Lint.lintProject(OptionalLintParameters optionalParams, String projectFilePath, FSharpOption`1 progress)
error :    at FSharpLint.Application.FSharpLintWorker.RunLint(String projectFile, OptionalLintParameters options, FSharpOption`1 progress)
error :    at FSharpLint.MSBuild.AppDomain.LintRunner.Lint(String projectFile)
error :    at FSharpLint.MSBuild.AppDomain.LintRunner.Lint(String projectFile)
error :    at FSharpLint.MSBuild.Proxy.Lint()
error :    at FSharpLint.MSBuild.FSharpLintTask.Execute()
```

### Known workarounds

Try the build again.  The race condition usually doesn't get triggered.

### Related information 

* Windows 10 Home 1709
* NuGet 0.9.1-beta release
* VS 2017 15.6.latest (but it's happened over multiple updates there)

**Comment by duckmatt** [comment]
Thanks for raising this, and sorry for the very delayed response! The MSBuild task has been deprecated, the linter is now best run as [dotnet tool](https://www.nuget.org/packages/dotnet-fsharplint/) or via Ionide
