### ISSUE TITLE
[CLI] - Can't specify a relative path on OSX.

### ISSUE THREAD

**Issue by ZaymonFC** [fsprojects/FSharpLint#367]
### Description
Using the CLI on OSX is cumbersome since you need to specify the full path to the project or solution file.

`dotnet fsharplint -f src/project-name/Project.fsproj` fails with:
```
Lint failed while analysing project ProjectName.fsproj.
Failed with: The path is empty.
Parameter name: path
Stack trace:   at System.IO.Path.GetFullPath(String path)
   at FSharpLint.Application.ConfigurationManagement.getParentDirectories(String path) in C:\projects\fsharplint-231\src\FSharpLint.Core\Application\Lint.fs:line 44
   at FSharpLint.Application.ConfigurationManagement.loadUserConfigFiles(String projectFilePath, Configuration defaultConfig) in C:\projects\fsharplint-231\src\FSharpLint.Core\Application\Lint.fs:line 53
   at FSharpLint.Application.Lint.loadConfigurationFilesForProject(String projectFilePath) in C:\projects\fsharplint-231\src\FSharpLint.Core\Application\Lint.fs:line 430
   at FSharpLint.Application.Lint.loadConfigAndParseFilesInProject@537(OptionalLintParameters optionalParams, String projectFilePath, FSharpFunc`2 projectProgress, FSharpFunc`2 warningReceived, FSharpChecker checker, FSharpList`1 files, FSharpProjectOptions projectOptions) in C:\projects\fsharplint-231\src\FSharpLint.Core\Application\Lint.fs:line 541
   at FSharpLint.Application.Lint.lintProject(OptionalLintParameters optionalParams, String projectFilePath) in C:\projects\fsharplint-231\src\FSharpLint.Core\Application\Lint.fs:line 547
   at FSharpLint.Console.Program.startWithArguments@171.Invoke(Argument arg) in C:\projects\fsharplint-231\src\FSharpLint.Console\Program.fs:line 179
```

### Expected behavior
Should be able to specify a relative path to any `.fsproj` or `.sln`

### Known workarounds
Specify the `absolute` path to the project or solution file.

### Related information
* Operating system: `OSX`
* .NET Runtime, CoreCLR or Mono Version: `.Net Core 3.0.100`

**Comment by ZaymonFC** [comment]
Resolved by #370
