### ISSUE TITLE
FSharp.Compiler.Service v34.0 seems to have had a breaking API change

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/FSharpLint#380]
### Description

After updating a Fake script to v5.19.1 from v5.19 (which updated from     FSharp.Compiler.Service (33.0.1) to FSharp.Compiler.Service (34.0.1))  and incidentally FSharpLint.Core from 0.12.5 to 0.12.10, the linting operation failed with exception

```
System.MissingMethodException: Method not found: 'FSharp.Compiler.SourceCodeServices.FSharpChecker FSharp.Compiler.SourceCodeServices.FSharpChecker.Create(Microsoft.FSharp.Core.FSharpOption`1<Int32>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Resolver>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`2<System.String,System.DateTime>,Microsoft.FSharp.Core.FSharpOption`1<System.Tuple`3<System.Object,IntPtr,Int32>>>>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>)'.
           at FSharpLint.Application.Lint.lintFile(OptionalLintParameters optionalParams, String filepath)
```

### Repro steps

Use the package versions specified above and run a Fake target like
```
_Target "Lint" (fun _ ->
  let failOnIssuesFound (issuesFound: bool) =
    Assert.That(issuesFound, Is.False, "Lint issues were found")
  try
    let settings =
      Configuration.SettingsFileName
      |> Path.getFullName
      |> File.ReadAllText

    let lintConfig =
      FSharpLint.Application.ConfigurationManagement.loadConfigurationFile settings
    let options =
      { Lint.OptionalLintParameters.Default with Configuration = Some lintConfig }

    !!"**/*.fsproj"
    |> Seq.collect (fun n -> !!(Path.GetDirectoryName n @@ "*.fs"))
    |> Seq.distinct
    |> Seq.map (fun f ->
         match Lint.lintFile options f with
         | Lint.LintResult.Failure x -> failwithf "%A" x
         | Lint.LintResult.Success w ->
           w
           |> Seq.filter (fun x ->
                match x.Fix with
                | None -> false
                | Some fix -> fix.FromText <> "AltCover_Fake")) // special case
    |> Seq.concat
    |> Seq.fold (fun _ x ->
         printfn "Info: %A\r\n Range: %A\r\n Fix: %A\r\n====" x.Info x.Range x.Fix
         true) false
    |> failOnIssuesFound
  with ex ->
    printfn "%A" ex
    reraise())
```
### Expected behavior

Linting happens

### Actual behavior

Exception thrown as above

### Known workarounds

Back off to previous tool versions.

### Related information

* Operating system - Windows
* Branch - NuGet released package
* .NET Runtime, CoreCLR or Mono Version - .net core 3.1.101

**Comment by duckmatt** [comment]
Thank you for the report, hopefully we should be on the updated fcs in the next day or so

**Comment by SteveGilham** [comment]
Still reproduces on v0.13.0
```
System.MissingMethodException: Method not found: 'FSharp.Compiler.SourceCodeServices.FSharpChecker FSharp.Compiler.SourceCodeServices.FSharpChecker.Create(Microsoft.FSharp.Core.FSharpOption`1<Int32>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>, Microsoft.FSharp.Core.FSharpOption`1<Resolver>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`2<System.String,System.DateTime>,Microsoft.FSharp.Core.FSharpOption`1<System.Tuple`3<System.Object,IntPtr,Int32>>>>, Microsoft.FSharp.Core.FSharpOption`1<Boolean>)'.           at FSharpLint.Application.Lint.lintFile(OptionalLintParameters optionalParams, String filepath)
```
with the fake task modified to take the FSharpLint API changes into account
```
_Target "Lint" (fun _ ->
  let failOnIssuesFound (issuesFound: bool) =
    Assert.That(issuesFound, Is.False, "Lint issues were found")
  try
    let settings =
      Configuration.SettingsFileName
      |> Path.getFullName
      |> File.ReadAllText

    let lintConfig =
      FSharpLint.Application.ConfigurationManagement.loadConfigurationFile settings
    let options =
      { Lint.OptionalLintParameters.Default with Configuration = Some lintConfig }

    !!"**/*.fsproj"
    |> Seq.collect (fun n -> !!(Path.GetDirectoryName n @@ "*.fs"))
    |> Seq.distinct
    |> Seq.map (fun f ->
         match Lint.lintFile options f with
         | Lint.LintResult.Failure x -> failwithf "%A" x
         | Lint.LintResult.Success w ->
           w
           |> Seq.filter (fun x ->
                match x.Details.SuggestedFix with
                | Some l -> match l.Force() with
                            | Some fix -> fix.FromText <> "AltCover_Fake" // special case
                            | _ -> false
                | _ -> false))
    |> Seq.concat
    |> Seq.fold (fun _ x ->
         printfn "Info: %A\r\n Range: %A\r\n Fix: %A\r\n====" x.Details.Message x.Details.Range x.Details.SuggestedFix
         true) false
    |> failOnIssuesFound
  with 
  | :? System.NullReferenceException ->
    printfn "MissingMethodException raised"
  | ex ->
    printfn "%A" ex
    reraise()
    )
```

**Comment by SteveGilham** [comment]
Is it possible that something flaky is going on with optional arguments in this `Create` call?

Adding 
```
    let where = typeof<FSharp.Compiler.SourceCodeServices.FSharpChecker>.Assembly
    printfn "%A" (where.GetName())
    typeof<FSharp.Compiler.SourceCodeServices.FSharpChecker>.GetMethods()
    |> Seq.iter (fun m -> printfn "%A" m.Name)
    typeof<FSharp.Compiler.SourceCodeServices.FSharpChecker>.GetMethod("Create").GetParameters()
    |> Seq.iter (fun m -> printfn "%A" m)
```
ahead of the `Lint.lintFile` yields
 ```
FSharp.Compiler.Service, Version=34.1.0.0, Culture=neutral, PublicKeyToken=null
"Create"
"MatchBraces"
...
Microsoft.FSharp.Core.FSharpOption`1[System.Int32] projectCacheSize
Microsoft.FSharp.Core.FSharpOption`1[System.Boolean] keepAssemblyContents
Microsoft.FSharp.Core.FSharpOption`1[System.Boolean] keepAllBackgroundResolutions
Microsoft.FSharp.Core.FSharpOption`1[FSharp.Compiler.ReferenceResolver+Resolver] legacyReferenceResolver
Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FSharp.Core.FSharpFunc`2[System.Tuple`2[System.String,System.DateTime],Microsoft.FSharp.Core.FSharpOption`1[System.Tuple`3[System.Object,System.IntPtr,System.Int32]]]] tryGetMetadataSnapshot   Microsoft.FSharp.Core.FSharpOption`1[System.Boolean] suggestNamesForErrors
Microsoft.FSharp.Core.FSharpOption`1[System.Boolean] keepAllBackgroundSymbolUses
Microsoft.FSharp.Core.FSharpOption`1[System.Boolean] enableBackgroundItemKeyStoreAndSemanticClassification
```
with 2 trailing `option bool` arguments above and beyond the ones in the missing method signature.

**Comment by SteveGilham** [comment]
More digging -- decompiling the v34.1 compiler services assembly shows that whether by design or oversight there's a parameter not marked as `[OptionalArgument]`
```
public static FSharpChecker Create([OptionalArgument] FSharpOption<int> projectCacheSize,
 [OptionalArgument] FSharpOption<bool> keepAssemblyContents,
 [OptionalArgument] FSharpOption<bool> keepAllBackgroundResolutions,
 [OptionalArgument] FSharpOption<ReferenceResolver.Resolver> legacyReferenceResolver,
 [OptionalArgument] FSharpOption<FSharpFunc<Tuple<string, DateTime>,
 FSharpOption<Tuple<object, IntPtr, int>>>> tryGetMetadataSnapshot,
 [OptionalArgument] FSharpOption<bool> suggestNamesForErrors,
 [OptionalArgument] FSharpOption<bool> keepAllBackgroundSymbolUses, 
[OptionalArgument] FSharpOption<bool> enableBackgroundItemKeyStoreAndSemanticClassification)
```
while decompiling the `Create()` call in FSharpLint 0.13.0 shows it's expanded to the missing method signature with fewer trailing arguments
```
	FSharpChecker checker = FSharpChecker.Create((FSharpOption<int>)null,
 (FSharpOption<bool>)null,
 (FSharpOption<bool>)null,
 (FSharpOption<Resolver>)null,
 (FSharpOption<FSharpFunc<Tuple<string, DateTime>, FSharpOption<Tuple<object, IntPtr,
 int>>>>)null,
 (FSharpOption<bool>)null);
``

**Comment by jgardella** [comment]
Awesome @SteveGilham, thanks for investigating. #378 to update FCS to v34.0.1 is still in review, I think let's wait until that gets merged and we push a new version, and see if it resolves the issue. If it doesn't we can continue investigating, and maybe reach out to the FCS maintainers.

**Comment by baronfel** [comment]
apologies for the API slippage on FCS, I missed this API in the merge. I've got an action item to add usage of the `dotnet synver` tool to the build process to help decide on what the correct version bump should be.

**Comment by jgardella** [comment]
Assuming this is fixed in FCS v34.0.1, v0.13.2 shouldn't have this issue. Appreciate if you could confirm @SteveGilham.

**Comment by baronfel** [comment]
Thanks to this issue in part I've added [new checks](https://github.com/fsharp/FSharp.Compiler.Service/pull/930) to the FCS build and deploy pipeline that ensure we follow semver rules.  Thanks for raising the alarm, @SteveGilham!

**Comment by SteveGilham** [comment]
This issue no longer reproduces with 0.13.2, now that I've tracked the FSharpLint API change between 0.13.1 and 0.13.2.
