### ISSUE TITLE
ArgumentOutOfRangeException while linting (FSharpLint.Core v0.13.2)

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/FSharpLint#386]
### Description

```
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FSharpLint.Framework.ParseFile.helper@141(FSharpLineTokenizer tokenizer, String line, FSharpTokenizerLexState tupledArg0, FSharpList`1 tupledArg1)
   at FSharpLint.Framework.ParseFile.tokenizeLine(FSharpLineTokenizer tokenizer, String line, FSharpTokenizerLexState initialState)
   at FSharpLint.Framework.ParseFile.helper@152-1(FSharpSourceTokenizer sourceTok, FSharpTokenizerLexState tupledArg0, Int32 tupledArg1, FSharpList`1 tupledArg2, FSharpList`1 tupledArg3)
   at FSharpLint.Framework.ParseFile.tokenizeLines(FSharpList`1 fileLines)
   at FSharpLint.Framework.Suppression.parseSuppressionInfo(FSharpList`1 lines)
   at FSharpLint.Framework.Suppression.getSuppressedRulesPerLine(FSharpSet`1 allRules, FSharpList`1 lines)
   at FSharpLint.Application.Lint.lint(LintInfo lintInfo, FileParseInfo fileInfo)
   at FSharpLint.Application.Lint.lintParsedFile(OptionalLintParameters optionalParams, ParsedFileInformation parsedFileInfo, String filepath)
```

### Repro steps

```
    let options =
      { Lint.OptionalLintParameters.Default with Configuration = FromFile (Path.getFullName "./fsharplint.json")  }
    Lint.lintFile options "./AltCover.fs"
```
where the files are here [fsharplint.0.13.2.zip](https://github.com/fsprojects/FSharpLint/files/4251560/fsharplint.0.13.2.zip)

### Expected behavior

A clean lint report as at 0.12.5

### Actual behavior

Exception as above

### Known workarounds

Dropping all affected tools back to last known good versions 

### Related information

* Operating system -- Windows 10 Home
* Branch -- NuGet release
* .NET Runtime, CoreCLR or Mono Version -- .net core 3.1.100
* Performance information, links to performance testing scripts -- n/a

**Comment by jgardella** [comment]
Thanks for the detailed report. I investigated with your example file and it seems the issue is coming up with your `#if NETCOREAPP2_0` line. Not sure why but the length of the whitespace token for the space between `#if` and the rest is 17, causing the code pulling out the token text using substring on the line to fail. I have updated it to to perform the substring based on the left and right column fo the token, rather than the length. Will push out a new version with the fix soon.

**Comment by jgardella** [comment]
@SteveGilham v0.13.3 is released with this fix, can you give it a try when you have a moment?

**Comment by SteveGilham** [comment]
This ran through for the whole project without raising any exceptions.  Thanks for the quick turn-around.

**Comment by milbrandt** [comment]
Thanks, I had the issue in https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/84 and wanted to investigate today. Thought I had broken something in upgrading from 0.12.
Unfortunatetly XML config is gone with 0.13.2 so there is no easy upgrade to fix it.
